import React, { createContext, useContext, useState } from "react";

type Lang = "ar" | "en";

const translations = {
  ar: {
    home: "الرئيسية",
    searchResults: "نتائج البحث",
    properties: "عقارات",
    mapSearch: "بحث بالخريطة",
    addProperty: "أضف عقارك",
    login: "تسجيل الدخول",
    register: "مستخدم جديد",
    forSale: "للبيع",
    forRent: "للإيجار",
    featured: "مميز",
    verified: "موثق",
    ownerCard: "صاحب الإعلان",
    advertiserVerified: "معلن موثق",
    online: "متصل الآن",
    offline: "غير متصل",
    seeAllListings: "شاهد كل إعلاناتي",
    sendMessage: "أرسل رسالة لصاحب الإعلان",
    messagePlaceholder: "أود الاستفسار عن هذا العقار، أرجو التواصل معي.",
    messageSent: "تم إرسال طلبك",
    messageSentSub: "سيتواصل معك صاحب الإعلان قريباً",
    propertyDescription: "وصف العقار",
    propertySpecs: "مواصفات العقار",
    amenities: "المميزات والخدمات",
    locationOnMap: "الموقع على الخريطة",
    viewMap: "انظر الخريطة",
    openInMaps: "فتح في خرائط جوجل",
    daysAgo: "أيام",
    views: "مشاهدة",
    safetyFirst: "سلامتك تهمنا",
    reportAbuse: "الإبلاغ عن إساءة",
    featuredAd: "إعلان مميز",
    revealPhone: "اضغط لإظهار الرقم",
    whatsapp: "واتساب",
    save: "حفظ",
    saved: "محفوظ",
    share: "مشاركة",
    copied: "تم النسخ!",
    similarProperties: "عقارات مشابهة",
    bedroom: "غرفة نوم",
    bath: "حمام",
    areaUnit: "م² مساحة",
    floor: "الطابق",
    category: "التصنيف",
    yearBuilt: "سنة البناء",
    totalFloors: "عدد الطوابق",
    refNumber: "الرقم المرجعي",
    dealType: "الحالة",
    areaSize: "المساحة",
    bedroomsSpec: "غرف النوم",
    bathsSpec: "الحمامات",
    yourName: "اسمك الكريم",
    yourPhone: "رقم الهاتف",
    send: "إرسال الرسالة",
    call: "اتصال",
    expand: "تكبير",
    perMonth: "/ شهر",
    search: "بحث",
    searchPlaceholder: "ابحث بالاسم أو المنطقة أو النوع...",
    searchNavPlaceholder: "ابحث عن شقة، فيلا، محل...",
    propertyType: "تصنيف العقار",
    subType: "نوع العقار",
    expectedPrice: "السعر المتوقع",
    anyPrice: "أي سعر",
    chooseType: "اختر التصنيف",
    chooseSubType: "اختر النوع",
    buyTab: "للبيع",
    rentTab: "للإيجار",
    viewAll: "عرض الكل",
    viewAllProperties: "عرض كل العقارات",
    viewAllAreas: "عرض كل المناطق",
    browsBy: "تصفح",
    browseByType: "تصفح حسب نوع العقار",
    browseSubtitle: "مجموعة متنوعة من العقارات تناسب جميع احتياجاتك",
    latest: "حصري",
    latestTitle: "أحدث العقارات المتاحة",
    latestSubtitle: "تمت إضافتها مؤخراً وحصرياً على منصتنا",
    explore: "استكشف",
    exploreTitle: "استكشف مناطق بنها",
    exploreSubtitle: "أشهر وأرقى أحياء بنها بأعداد العقارات المتاحة",
    agent: "وكيل عقاري",
    joinTitle: "هل تريد بيع أو تأجير عقارك؟",
    joinSubtitle: "سجل عقارك الآن مجاناً وسنتولى الباقي لضمان وصوله لآلاف المهتمين",
    addNow: "أضف عقارك الآن",
    contactUs: "تواصل معنا",
    registerFree: "سجل مجاناً",
    properties_count: "عقار",
    signIn: "تسجيل",
    dashboard: "لوحة تحكم",
  },
  en: {
    home: "Home",
    searchResults: "Search Results",
    properties: "Properties",
    mapSearch: "Map Search",
    addProperty: "Add Property",
    login: "Login",
    register: "New User",
    forSale: "For Sale",
    forRent: "For Rent",
    featured: "Featured",
    verified: "Verified",
    ownerCard: "Ad Owner",
    advertiserVerified: "Verified Advertiser",
    online: "Online Now",
    offline: "Offline",
    seeAllListings: "See All My Listings",
    sendMessage: "Send Message to Ad Owner",
    messagePlaceholder: "I would like to inquire about this property, please contact me.",
    messageSent: "Message Sent",
    messageSentSub: "The ad owner will contact you soon",
    propertyDescription: "Property Description",
    propertySpecs: "Property Specifications",
    amenities: "Amenities & Services",
    locationOnMap: "Location on Map",
    viewMap: "View Map",
    openInMaps: "Open in Google Maps",
    daysAgo: "days ago",
    views: "views",
    safetyFirst: "Your Safety Matters",
    reportAbuse: "Report Abuse",
    featuredAd: "Featured Ad",
    revealPhone: "Click to Show Number",
    whatsapp: "WhatsApp",
    save: "Save",
    saved: "Saved",
    share: "Share",
    copied: "Copied!",
    similarProperties: "Similar Properties",
    bedroom: "Bedrooms",
    bath: "Bathrooms",
    areaUnit: "m² Area",
    floor: "Floor",
    category: "Category",
    yearBuilt: "Year Built",
    totalFloors: "Total Floors",
    refNumber: "Reference No.",
    dealType: "Deal Type",
    areaSize: "Area",
    bedroomsSpec: "Bedrooms",
    bathsSpec: "Bathrooms",
    yourName: "Your Name",
    yourPhone: "Phone Number",
    send: "Send Message",
    call: "Call",
    expand: "Expand",
    perMonth: "/ month",
    search: "Search",
    searchPlaceholder: "Search by name, area or type...",
    searchNavPlaceholder: "Search for apartment, villa, shop...",
    propertyType: "Property Type",
    subType: "Sub Type",
    expectedPrice: "Expected Price",
    anyPrice: "Any Price",
    chooseType: "Choose Type",
    chooseSubType: "Choose Sub Type",
    buyTab: "For Sale",
    rentTab: "For Rent",
    viewAll: "View All",
    viewAllProperties: "View All Properties",
    viewAllAreas: "View All Areas",
    browsBy: "Browse",
    browseByType: "Browse by Property Type",
    browseSubtitle: "A variety of properties to suit all your needs",
    latest: "Exclusive",
    latestTitle: "Latest Available Properties",
    latestSubtitle: "Recently added exclusively on our platform",
    explore: "Explore",
    exploreTitle: "Explore Banha Areas",
    exploreSubtitle: "The most prestigious neighborhoods in Banha",
    agent: "Real Estate Agent",
    joinTitle: "Want to sell or rent your property?",
    joinSubtitle: "List your property for free and we'll take care of the rest",
    addNow: "Add Your Property Now",
    contactUs: "Contact Us",
    registerFree: "Register Free",
    properties_count: "properties",
    signIn: "Sign In",
    dashboard: "Dashboard",
  },
};

export type TranslationKey = keyof typeof translations.ar;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ar",
  setLang: () => {},
  t: (key) => translations.ar[key],
  isRTL: true,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("ar");
  const t = (key: TranslationKey): string =>
    (translations[lang] as Record<string, string>)[key] ?? (translations.ar as Record<string, string>)[key] ?? key;
  const isRTL = lang === "ar";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
